#!/bin/bash

mongod=/home/app/ngoss/mongodb/bin/mongod
mongod_config=/etc/mongod.conf
prog="mongod"
RETVAL=0

# Source function library.
. /etc/rc.d/init.d/functions

stop() {
    grep_mongo=`ps aux | grep -v grep | grep "${mongod}"`
    if [ ${#grep_mongo} -gt 0 ]
    then
        echo "Stop MongoDB."
        PID=`ps x | grep -v grep | grep "${mongod}" | awk '{ print $1 }'`
        `kill -2 ${PID}`
        RETVAL=$?
    else
        echo "MongoDB is not running."
    fi
}
start() {
    grep_mongo=`ps aux | grep -v grep | grep "${mongod}"`
    if [ -n "${grep_mongo}" ]
    then
        echo "MongoDB is already running."
    else
        echo "Start MongoDB."
        `${mongod} --config ${mongod_config}`
        RETVAL=$?
    fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo $"Usage: $prog {start|stop|restart}"
        exit 1
esac

exit $RETVAL
